### ISSUE TITLE
Peer to Peer Review

### ISSUE THREAD

**Issue by Olamarx** [ElsonOtake/TodoList#4]
<img src="https://media2.giphy.com/media/3oz8xVjxTPNEzyKRKU/giphy.gif"/>

@ElsonOtake, indeed you have done a good job.
However, I feel you can still work on the delete button as it doesn't delete except the input is empty.

Again, job well done!

**Comment by ElsonOtake** [comment]
The delete button works as per the example video, but your observation is valid. I changed the button functionality as you advised.
